### ISSUE TITLE
Can we use "WebService" data source?

### ISSUE THREAD

**Issue by oanqa** [belgattitude/soluble-jasper#1]
I want to use [WebService](https://community.jaspersoft.com/project/web-service-data-source) data source in our report. I've already tried with your jasper-bridge and it throw error. Can you help me?

```
Filling report 'EditingSchedule.v2.jrxml' failed with 'JavaProxiedException' (Error filling report "reports/location/EditingSchedule.v2.jrxml". [net.sf.jasperreports.engine.fill.JRExpressionEvalException]: Invoke failed: [[c:JasperFillManager]]->fillReport((o:JasperReport)[o:JasperReport], (i:Map)[o:HashMap], (i:JRDataSource)[o:JREmptyDataSource]). Cause: net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: ((net.sf.jasperreports.engine.data.JsonDataSource)$P{REPORT_DATA_SOURCE}).subDataSource("schedules") VM: 1.8.0_191@http://java.oracle.com/ (net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: ((net.sf.jasperreports.engine.data.JsonDataSource)$P{REPORT_DATA_SOURCE}).subDataSource("schedules") VM: 1.8.0_191@http://java.oracle.com/))  
```

and thank you for your hard work in this project.

**Comment by oanqa** [comment]
Using the adapter is working if using tomcat to deploy JavaBridge and add WebService applicationContext bean manually to WEB-INF.
Are there some way to include the bean xml to springboot? 
I'm already try to load it with @ImportResource and no result (i don't know spring or java stuff)
Just asking here if somehow you can help me to use the adapter. thank you

**Comment by belgattitude** [comment]
> Using the adapter is working if using tomcat to deploy JavaBridge and add WebService applicationContext bean manually to WEB-INF.

Yes you can always add libraries in the WEB-INF folder... I'm not working with the bridge anymore, but generally I generates a full .war file with gradle. 

As an example look at what I'm doing on travis:

https://github.com/belgattitude/soluble-jasper/blob/master/.travis/build_javabridge_jasper_war.sh

and the corresponding gradle config

https://github.com/belgattitude/soluble-jasper/blob/master/.travis/init.jasperreport.gradle

You can try to modify it, including local files or a repository. 

Hope it helps

**Comment by belgattitude** [comment]
BTW, for spring boot have a look to 

https://github.com/belgattitude/pjb-starter-springboot


```sh
$ ./gradlew build -I init-scripts/init.jasperreports.gradle -I init-scripts/init.mysql.gradle
```

See some examples of init-scripts that can be used to include libraries:

https://github.com/belgattitude/pjb-starter-springboot/tree/master/init-scripts

**Comment by oanqa** [comment]
We are using https://github.com/belgattitude/pjb-starter-springboot for building the java bridge server and we the the init-scripts. But we cannot add the beans xml of WebServiceAdapter to from the init-scripts (we don't know how to load it).

thank you for reply

**Comment by belgattitude** [comment]
Is this helping ?

https://stackoverflow.com/questions/25495629/how-can-i-use-spring-boot-auto-configured-beans-in-xml-configuration-files

http://www.springboottutorial.com/spring-boot-java-xml-context-configuration

PS: is it relevant to use bean based annotations ?
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-java-basic-concepts

**Comment by oanqa** [comment]
> Is this helping ?
> 
> https://stackoverflow.com/questions/25495629/how-can-i-use-spring-boot-auto-configured-beans-in-xml-configuration-files
> 
> http://www.springboottutorial.com/spring-boot-java-xml-context-configuration

I've already tried to using @ImportResource and spring boot exited without any logs. Maybe i'll try again next time.

> PS: is it relevant to use bean based annotations ?

So we must create class for the datasource adapter in spring boot and use annotation reflecting the xml right? i'll try it later

Thank you so much for your help.
